### ISSUE TITLE
I am not able to import torched module ..

### ISSUE THREAD

**Issue by dishantamin** [shivamsaboo17/ManifoldMixup#2]
Hello, can you please help me find the torched module in your code .. I am not able to Import it.

from torched.customs.layers import LinearLayer, Flatten
from torched.trainer_utils import Train

**Comment by shivamsaboo17** [comment]
@dishantamin torched is my own custom library to train neural networks (mostly implementations of a few custom layers, algorithms, optimizers etc). I haven't open sourced it yet as it is very hacky and I created it as a hobby project. 

You can write your own training loop as usual in Pytorch or use some higher level api's as well such as fast.ai or pytorch lightning. The manifold mixup code is independent of the torched library.

**Comment by dishantamin** [comment]
Thank you so much.
